import * as React from "react";
import Head from "next/head";
import Grid from "@mui/material/Grid2";
import { DataGrid } from "@mui/x-data-grid";
import { tableLive } from "../strucTables";
import {
  Card,
  Container,
  CardHeader,
  CardContent,
  Typography,
} from "@mui/material";
import { signIn, signOut, useSession } from "next-auth/react";
import { useState, useEffect } from "react";

export default function Home() {
  const { data: session, status } = useSession() as {
    data: { user: { isAdmin: boolean } } | null;
    status: string;
  };
  const [live, setLive] = useState<Array<any>>();
  const [isAuthorized, setIsAuthorized] = useState<boolean>(false);
  useEffect(() => {
    if (status === "authenticated") {
      fetch("/api/getHistoric", { method: "POST" })
        .then((response) => response.json())
        .then((res) => {
          setLive(res);
        });
      if (session?.user.isAdmin === false) {
        setIsAuthorized(false);
      } else {
        setIsAuthorized(true);
      }
    } else {
      setIsAuthorized(false);
    }
  }, []);

  return (
    <>
      <Head>
        <title>PROJET INDUSTRIEL</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isAuthorized ? (
        <Container maxWidth="xl" sx={{ mt: 4 }}>
          <Grid container spacing={2}>
            <Grid size={12}>
              <Card>
                <CardHeader title="Relais" />
                <CardContent>
                  <DataGrid columns={tableLive} hideFooter rows={live} />
                </CardContent>
              </Card>
            </Grid>
          </Grid>
        </Container>
      ) : (
        <Card>
          <Typography>
            Vous n'êtes pas autorisé à accéder à cette page du ternet
          </Typography>
        </Card>
      )}
    </>
  );
}
