import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Container from "@mui/material/Container";
import Card from "@mui/material/Card";
import CardHeader from "@mui/material/CardHeader";
import CardContent from "@mui/material/CardContent";
import Button from "@mui/material/Button";
import Typography from "@mui/material/Typography";
import Avatar from "@mui/material/Avatar";
import Box from "@mui/material/Box";

export default function Home() {
  const { data: session } = useSession();

  return (
    <>
      <Head>
        <title>PROJET INDUSTRIEL</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxWidth="xl" sx={{ mt: 4 }}>
        <Card sx={{ p: 2, boxShadow: 3 }}>
          <CardHeader
            avatar={
              session?.user.image ? (
                <Avatar
                  alt={session.user.name || ""}
                  src={session.user.image || ""}
                />
              ) : (
                <Avatar>{session?.user.name?.charAt(0)}</Avatar>
              )
            }
            title={
              session
                ? `Connecté en tant que ${session.user.name}`
                : "Non connecté"
            }
            subheader={session?.user.email}
          />
          <CardContent>
            <Typography variant="body1">
              {session?.user.isAdmin
                ? "Vous êtes admin"
                : "Vous n'êtes pas admin"}
            </Typography>
            <Box mt={2}>
              {session ? (
                <Button
                  variant="contained"
                  color="primary"
                  onClick={() => signOut()}>
                  Déconnexion
                </Button>
              ) : (
                <Button
                  variant="contained"
                  color="primary"
                  onClick={() => signIn()}>
                  Connexion
                </Button>
              )}
            </Box>
          </CardContent>
        </Card>

        <Card sx={{ mt: 4, p: 4 }}>
          <Typography variant="h4" gutterBottom>
            Projet Industriel
          </Typography>
          <Typography variant="body1">
            Ce projet industriel est une application web qui permet de
            visualiser les données en temps réel d'un système industriel. On
            reprends les données via des capteurs, celles-ci sont transféré de
            l'automate a un node-red via le protocol OPC-UA.
          </Typography>
        </Card>
      </Container>
    </>
  );
}
